site_name: Tommy Jun 2026 eDo Testing Practice
site_description: 'End-to-end testing documentation and result report for OCP test cases'
site_author: 'Tommy'

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - sql
    - json

nav:
  - Home: index.md

  - Test Cases:
      - SF_E2E_OCP_016 (First Call Activation): test-cases/SF_E2E_OCP_016.md
      - SF_E2E_OCP_058 (Modify Offer IPP): test-cases/SF_E2E_OCP_058.md
      - SF_E2E_OCP_159 (Reconnection Postpaid): test-cases/SF_E2E_OCP_159.md
      - E2E_OCP_SF022 (Cancel Postdating): test-cases/E2E_OCP_SF022.md
      - SF_E2E_OCP_162 (Reconnection >180 Days): test-cases/SF_E2E_OCP_162.md
      - SF_E2E_OCP_188 (Starter Pack Activation): test-cases/SF_E2E_OCP_188.md
      - SF_E2E_OCP_018 (SIM Replacement): test-cases/SF_E2E_OCP_018.md
      - SF_E2E_OCP_085 (Change Main Offer): test-cases/SF_E2E_OCP_085.md
      - SF_E2E_OCP_001 (New Connection Prepaid): test-cases/SF_E2E_OCP_001.md
      - SF_E2E_OCP_126 (Transfer Ownership): test-cases/SF_E2E_OCP_126.md

plugins:
  - search

markdown_extensions:
  - tables
  - fenced_code
  - pymdownx.details
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: true
